### ISSUE TITLE
How to determine the equilibrium configurations of Na_4Cl_4 clusters for tetramers (n=4)?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G1#21]
Can you please explain this?

**Comment by LinxuanHu** [comment]
at equilibrium, it will have the lowest potential energy, you can find the equation to determine the potential in the link below
https://github.com/ubsuny/CompPhys/blob/main/MinMax/nacl.ipynb

**Comment by tirthbha** [comment]
@reshnashrestha For the convenience, we can start to assign the initial position by choosing origin as reference so that we can guess other positions with the help of figure shown in the paper.

**Comment by reshnashrestha** [comment]
Yeah that can be done.
