### ISSUE TITLE
Difference between different configuration

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework7G1#22]
What exactly is the difference between different configuration? It seems that the final potential energy after optimization is different ? Any idea how we start with the initial idea position ?

**Comment by reshnashrestha** [comment]
Yeah the diff is the binding energy per ion pairs. I am also not sure on how to start.

**Comment by tirthbha** [comment]
@pratibha77118 Hope now you got the idea.

**Comment by pratibha77118** [comment]
Along with binding energy per ion there is difference in orientations of ions after optimization for different configurations.
