### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework7G1#3]
i can be the maintainer

**Comment by reshnashrestha** [comment]
@LinxuanHu who are the other group members? May be because of break, lots are passive including me.

**Comment by LinxuanHu** [comment]
@pratibha77118 and @tirthbha are also in G1

**Comment by tirthbha** [comment]
@LinxuanHu Are you the maintainer now?

**Comment by pratibha77118** [comment]
@LinxuanHu @tirthbha who will be the maintainer ?

**Comment by LinxuanHu** [comment]
i will be the maintainer, but haven't get access yet

**Comment by tirthbha** [comment]
@LinxuanHu You can text to Professor in dicsord.

**Comment by LinxuanHu** [comment]
> @LinxuanHu You can text to Professor in dicsord.

did it
