### ISSUE TITLE
Why doesn't the Compphys notebook show any interactive plot? 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework7G1#37]
<img width="1051" alt="Screenshot 2023-11-30 at 12 03 18 AM" src="https://github.com/ubsuny/23-Homework7G1/assets/66480280/568e11a7-8049-41e2-9097-e0323f32434f">

**Comment by tirthbha** [comment]
It is working on my notebook. Have you checked using quantum lab or any other platform?

**Comment by Mosaddeq107** [comment]
> It is working on my notebook. Have you checked using quantum lab or any other platform?

No, I tried Google Colab and CodeSpace
