### ISSUE TITLE
Showing interactive plot: Solved

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework7G1#41]
If you encountered the problem of getting the interactive plot in the Jupyter notebook, you could replace the first line **_%matplotlib notebook_** with **_%matplotlib inline_** as shown in the figure. 

<img width="994" alt="Screenshot 2023-11-30 at 8 02 05 AM" src="https://github.com/ubsuny/23-Homework7G1/assets/66480280/dc09491e-ddf6-4b9b-b9ac-a79e87865733">

**Comment by uarif** [comment]
Yes, exactly
