### ISSUE TITLE
Cubic Rectangular Configurations

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G1#58]
I have completed the over all tasks under this topic and the my work is summarized in:
[cubic_rectangular_configurations.md](https://github.com/ubsuny/23-Homework7G4/blob/main/cubic_rectangular_configurations.md)

**Comment by tirthbha** [comment]
@reshnashrestha Is linting necessary for this task?

**Comment by pratibha77118** [comment]
@tirthbha yes it is mentioned in the task to do the lint but pytest is not required.

**Comment by reshnashrestha** [comment]
Have you guys done this ?
