### ISSUE TITLE
Did everyone use the BFGS method or did you try to find better algorithms?

### ISSUE THREAD

**Issue by AhmedCode99** [ubsuny/23-Homework7G1#69]

**Comment by pratibha77118** [comment]
@ yes I used the same.Also on  using the CG method also I get the same.

**Comment by pratibha77118** [comment]
@AhmedCode99 did you check with different method to see the difference in values and position obtained?

**Comment by AhmedCode99** [comment]
This is interesting and somewhat useful, THANK YOU
