### ISSUE TITLE
Merge Request 

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework7G1#78]
@LinxuanHu I have added some more details in the documentation file. Please accept the request. 
@pratibha77118 Hope, we are finally done, right?

**Comment by pratibha77118** [comment]
@tirthbha I do have pulled the merge request.

**Comment by LinxuanHu** [comment]
all requests have been merged

**Comment by AhmedCode99** [comment]
ALWAYS SUBMITTING AT THE LAST HOUR. KEEPS THINGS INTRESTING
