### ISSUE TITLE
Name for seventh configurations chosen.

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework7G1#79]
Hi all,
I am having confusion with the name of seventh configuration chosen. I used the configuration and defined position coordinates thinking the name of configurations as square planar and tetrahedron. If any one have done the same configuration please suggest me how you have chosen the structure. If possible indicate the source you have used.

**Comment by LinxuanHu** [comment]
use potential energy?

**Comment by pratibha77118** [comment]
Thanks for informing. I have used different names for it.
