### ISSUE TITLE
are we supposed to keep unittesting.yml file?

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework7G1#8]
As described in hw task, no unit tests are necessary, what's the point of unittesting.yml?

**Comment by LinxuanHu** [comment]
just keep it since it's already there

**Comment by tirthbha** [comment]
@reshnashrestha I think it's not necessary for this task.

**Comment by reshnashrestha** [comment]
Yes so it will be okay to remove it?

**Comment by Mosaddeq107** [comment]
> Yes so it will be okay to remove it?

You don't need to remove it, but you can do it.

**Comment by reshnashrestha** [comment]
Okay, make sense.
