### ISSUE TITLE
Value of a and b for rectangular distorted structure

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework7G1#83]
@tirthbha how did you chosed the value of a and b for  rectangular distorted structure. Is that any specific region for the values chosen?

**Comment by tirthbha** [comment]
@pratibha77118 For the rectangle, require length(a), width(b) and height (a), I assumed length and height same but different width. This is just for simplicity.

**Comment by AhmedCode99** [comment]
This is interesting and somewhat useful
